version: '3.7'

services:

  expense-api:
    container_name: expense-api
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    depends_on: 
      - mssql
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - demo-cqrs

  expense-frontend:
    container_name: sba.expense.ui
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development